### ISSUE TITLE
A full CRUD example, with listing, would be nice

### ISSUE THREAD

**Issue by kkinder** [aarondfrancis/vue-model#12]
Since I'm relatively new to Vue.JS, I'm having trouble putting together how I would actually use vue-model to connect to a restful JSON API and write a real application.

Something as simple as a complete CRUD example app would be nice, like a TODO list.

**Comment by thorsteneckel** [comment]
Hi @kkinder - I don't think that I'll find the time to create a full example RESTful JSON API. So there is any help welcome.

I'm currently working on a Rails + Devise Token Auth + Webpack + Vue + Axios + vue-model boilerplate application. Maybe that's interesting for you?

**Comment by kkinder** [comment]
Yeah, that would be helpful. I'm using a different backend, but any examples help. :) It's just a bit of an undertaking to figure it all out from scratch.

**Comment by FlappyHeart** [comment]
I just write a lot of ugly code to implement the same feature as this repo did. And for anyone else I will try to make some examples later. :)
