### ISSUE TITLE
[Question] Pass headers in http actions

### ISSUE THREAD

**Issue by jjcodes78** [aarondfrancis/vue-model#2]
I can do this?

**Comment by aarondfrancis** [comment]
You can't right now, but that would be a good addition. I'll see if I can add it in today or tomorrow!

Thanks for the question.

**Comment by devplayer0** [comment]
This would be great for authentication. For example my backend uses JWT for auth and reads the token from the HTTP `Authorization` header.

**Comment by stefanosandes** [comment]
+1

**Comment by aarondfrancis** [comment]
@jjsquad @jackos2500 @stefanosandes please take a look at the open PR https://github.com/aarondfrancis/vue-model/issues/3 and let me know if this would work for JWT and whatever else you had in mind.

**Comment by aarondfrancis** [comment]
You can see a description of the functionality in the README diff.

**Comment by devplayer0** [comment]
@aarondfrancis Looks good to me, I'm using JWT.

**Comment by jjcodes78** [comment]
Thanks @aarondfrancis ;)

**Comment by stefanosandes** [comment]
Great! Thanks @aarondfrancis!  But how could I set the headers later, after Vue.use(...) . There may be cases where a token expires and we need to redefine it without reloading the page .

**Comment by aarondfrancis** [comment]
@stefanosandes In that case, it would be best to make `headers` a callback function.

``` javascript
Vue.use(require('vue-model'), {
    headers: function(action) {
        return {
            'Authorization': getTokenFromStorage()
        };
    }
});
```

I'm open to other suggestions, of course.

**Comment by devplayer0** [comment]
@stefanosandes According to the README in the PR you can also set the headers on a per-`action` basis, again with either a function or just a plain object.

**Comment by aarondfrancis** [comment]
@jackos2500 that's correct, but I'm not sure that would help @stefanosandes if the token changes _after_ he defines the headers, either by general or action-specific definitions.

**Comment by stefanosandes** [comment]
@aarondfrancis callback makes perfect sense. Thank you! It was very excellent!

**Comment by aarondfrancis** [comment]
Great! I'll merge it in tonight.

**Comment by devplayer0** [comment]
@aarondfrancis But with a function in the `action` you can override the global headers option at the time the request is sent right?
Like this:

``` javascript
Vue.models.register('video', {
     actions: {
         complete: {
             method: 'POST',
             route: '/{id}/complete',
             headers: function() {
                return {
                   "Authorization": getTokenFromStorage()
                };
             }
         }
     }
 });
```

**Comment by aarondfrancis** [comment]
@jackos2500 Yep, correct! You can use a function in the action definition or globally in the model registration. For each action, the action-specific definition will extend and override the global options.

Here's the logic that handles that: https://github.com/aarondfrancis/vue-model/pull/3/files#diff-96402e3967f40f890b345d1291b004b3R230
