### ISSUE TITLE
Vue not defined and $ not defined

### ISSUE THREAD

**Issue by jjcodes78** [aarondfrancis/vue-model#4]
Hi again!

I use webpack vue-cli in my Vue's projects, and in this case this 2 warnings appears.

My "temp non clean" solution:
after import Vue from 'vue', I put window.Vue = Vue... and the same occurs with $ (from jQuery)... I think that be possible to update registering vue-model as plugin, and the ajax calls sending by vue-resource (for best compatibility) with lib :)

Sorry for my bad english!
Thats it! Cya

**Comment by aarondfrancis** [comment]
@jjsquad I would like to transition from jQuery to vue-resource at some point. I'm not sure at the moment how to solve for the `Vue not defined` issue. Thoughts?

**Comment by aarondfrancis** [comment]
@jjsquad check out #5 and see if that gets rid of the need for Vue being a global variable. If it does, I'll merge and close this issue and open a new one for transitioning away from `$` to vue-resource.

**Comment by jjcodes78** [comment]
I'll try it and report.

Thanks

**Comment by jjcodes78** [comment]
@aarondfrancis Worked like a charm! :) 
Thank you!
Next step... vue-resource I guess. Cya!
