### ISSUE TITLE
Support sending (create, update) as JSON

### ISSUE THREAD

**Issue by iiome** [aarondfrancis/vue-model#9]
vue-model already supports loading data as JSON (fetch, list). Would it be possible to support  sending (create, update) data as JSON?

**Comment by thorsteneckel** [comment]
Hi @iiome - do I get your right that you want so send a JSON string (not an JS Object) via create/update through vue-model?

**Comment by iiome** [comment]
Quite the opposite! I'd like vue-model to transform to JSON the Javascript object it received when the contentType is set to application/json. I've committed some code on July 24th about this.
